name: Jalankan Python Script

on:
  workflow_dispatch:      # Tombol manual
  schedule:
    - cron: '*/30 * * * *' # OTOMATIS 30 MENIT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # INI KUNCINYA (Naik ke 3.12)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas-ta # Versi 3.12 pasti bisa baca ini
          pip install -r requirements.txt

      - name: Run script
        run: python mesin_analisis.py
