name: Jalankan Python Script

on:
  workflow_dispatch:      # Tombol manual
  schedule:
    - cron: '*/30 * * * *' # OTOMATIS 30 MENIT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Tetap 3.12 karena ini sudah sukses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests     # INI YANG SAYA TAMBAHKAN
          pip install pandas-ta    # Ini alat yang tadi
          pip install -r requirements.txt

      - name: Run script
        run: python mesin_analisis.py
